Feature/getting touchy with items
GothicVRProject/GothicVR pull request #130
Opened 2023-06-29 20:23 UTC by JaXt0r

# Checklist

## Scene
* [ ] FeatureFlags reverted to right value

## Dependencies
* [ ] If libphoenix-shared.dll is changed, .so is also changed

Can be merged after: https://github.com/GothicKit/phoenix-csharp-interface/pull/16

2023-06-30 05:36 UTC, JaXt0r commented
Please review.

What's working now:   
**VobItems can now be grabbed and once they're in your hand for the first time, physics are applied.**

2023-06-30 05:56 UTC, Tyroonis commented
Solved the merge conflicts

2023-06-30 06:00 UTC, Tyroonis commented
@JaXt0r 

Kannst du nochmal nach den dll schauen?
```
Assets/GothicVR/Scripts/Creator/MusicCreator.cs(36,17): error CS0246: The type or namespace name 'PxVmMusicData' could not be found (are you missing a using directive or an assembly reference?)
*** Tundra build failed (31.49 seconds), 858 items updated, 866 evaluated
## Script Compilation Error for: Csc Library/Bee/artifacts/2400b0aEDbg.dag/Assembly-CSharp.dll (+2 others)
## CmdLine: "/opt/unity/Editor/Data/NetCoreRuntime/dotnet" exec "/opt/unity/Editor/Data/DotNetSdkRoslyn/csc.dll" /nostdlib /noconfig /shared "@Library/Bee/artifacts/2400b0aEDbg.dag/Assembly-CSharp.rsp" "@Library/Bee/artifacts/2400b0aEDbg.dag/Assembly-CSharp.rsp2"
## Output:
Assets/GothicVR/Scripts/Creator/MusicCreator.cs(36,17): error CS0246: The type or namespace name 'PxVmMusicData' could not be found (are you missing a using directive or an assembly reference?)
```

2023-06-30 06:10 UTC, JaXt0r commented
Merging main into branch can cause errors on the DLLs. It seems, that you overwrote changes I have made in the correlated branches of phoenix. Please revert the commit. @Tyroonis 

But still it's a good point to test with main branch included. I will add this as a checkbox for PRs.

2023-06-30 06:23 UTC, Tyroonis commented
> Merging main into branch can cause errors on the DLLs. It seems, that you overwrote changes I have made in the correlated branches of phoenix. Please revert the commit. @Tyroonis
> 
> But still it's a good point to test with main branch included. I will add this as a checkbox for PRs.

I have not merget main .
That was an automatic naming when resolving the merge conflicts. 
The dll files had conflicts. But I took the commit back.
Please see for yourself.

2023-06-30 07:55 UTC, JaXt0r commented
@Romeeey @JucanAndreiDaniel @Tyroonis DLLs etc. fixed. Feel free to test it again.

2023-06-30 12:15 UTC, JucanAndreiDaniel requested changes
Add the libphoenix so and it's good to go for me

2023-06-30 17:12 UTC, JaXt0r commented
I fixed another issue: We now load all VobItems (needed to INSTANCiate them)

![image](https://github.com/GothicVRProject/GothicVR/assets/120568393/26f896de-c0d7-48fd-b010-9b4daf236822)

2023-07-01 20:29 UTC, JaXt0r commented
PR solves this ticket additionally: https://github.com/GothicVRProject/GothicVR/issues/132

2023-07-02 15:28 UTC, JucanAndreiDaniel requested changes
LGTM code-wise except music part, I'll approve after testing on headset

2023-07-02 15:28 UTC, JucanAndreiDaniel commented on Assets/GothicVR/Scripts/Creator/MusicCreator.cs
Maybe it would be better to revert the commit for this file to not have a merge conflict with main

2023-07-02 23:19 UTC, JucanAndreiDaniel approved these changes
LGTM

2023-07-03 03:48 UTC, merged