Feature/improved turnsettings
GothicVRProject/GothicVR pull request #174
Opened 2023-08-02 16:02 UTC by Romeeey

# To test
* [ ] Open Settings menu and check if turn speed slider is there
* [ ] Change slider and see how turning gets slower and faster
* [ ] Check for snapturn and continuous turn
* [ ] Check if items push you back when you move them to your body center (It should not)
* [ ] Walk behind the menu (it should not be invisible anymore, although flipped)

# Checklist
(Please judge for yourself which entry is valuable for your PR)

## Scene
* [ ] FeatureFlags reverted to right value

# Testing
* [ ] Merged _main_ into this branch and tested with the latest features
* [ ] Tested with PCVR
* [ ] Tested with Pico / Quest

## Dependencies
* [ ] If libphoenix-shared.dll is changed, .so is also changed

2023-08-02 22:28 UTC, JucanAndreiDaniel requested changes
Bootstrap.unity seem to still have merge issues, please fix this before i can test

2023-08-04 18:28 UTC, JaXt0r requested changes
Just a few question and name improvements. I will test it after changes are done.

2023-08-04 18:28 UTC, JaXt0r commented on Assets/GothicVR/Resources/Materials/BackgroundMaterial.mat.rej
Is this file needed? It's content look like it's some leftover from a merge?

2023-08-04 18:28 UTC, JaXt0r commented on Assets/GothicVR/Scenes/Bootstrap.unity
> +<<<<<<< HEAD
Merge issues. Please solve. From what I see, I think the first one is right. The other doesn't contain any value.

2023-08-04 18:28 UTC, JaXt0r commented on Assets/GothicVR/Scripts/Manager/ConstantsManager.cs
> +        public string turnAngelPlayerPref = "TurnAngelSetting";
```suggestion
        public string turnAnglePlayerPref = "TurnAngleSetting";
```

Angel == 🎣 in German
Angle == 📐in English
;-)

2023-08-04 18:28 UTC, JaXt0r commented on Assets/GothicVR/Scripts/UI/TurnAngelController.cs
> +public class TurnAngelController : MonoBehaviour
```suggestion
public class TurnAngleController : MonoBehaviour
```

2023-08-16 21:29 UTC, Romeeey commented on Assets/GothicVR/Scenes/General.unity
> -      objectReference: {fileID: 0}
No. I'll revert.

2023-08-16 21:38 UTC, Romeeey commented on Assets/GothicVR/Resources/Materials/BackgroundMaterial.mat.rej
not needed.

2023-08-16 21:44 UTC, Romeeey commented on Assets/GothicVR/Scripts/UI/TurnAngelController.cs
> +        turnangelslider.value = PlayerPrefs.GetFloat(ConstantsManager.I.turnAngelPlayerPref, 45);
Followed your suggestions. Movespeed and turnangel can now be configured in the constants manager.

2023-08-17 04:39 UTC, JaXt0r requested changes
Just a few typos and some ideas left:
1. I found out how to flip the image for back side of the menu. I couldn't find how you apply "back side" but you can easily create the flipped image. https://discussions.unity.com/t/flipping-texture/51754/3
![image](https://github.com/GothicVRProject/GothicVR/assets/120568393/19d934ce-e853-4faf-8dec-f9c3378abebd)
Alternative is to have a second mesh which is same pixel dimensions but turned.
2. I remember Frank built, that we can close the menu via >A< again. Is this only in main?
3. You need to merge main into this branch. Let me provide you some help.

2023-08-17 04:39 UTC, JaXt0r commented on Assets/GothicVR/Scenes/Bootstrap.unity
> +  turnAngelPlayerPref: TurnAngelSetting
```suggestion
  turnAnglePlayerPref: TurnAngleSetting
```

2023-08-17 04:39 UTC, JaXt0r commented on Assets/GothicVR/Scripts/UI/TurnAngelController.cs
Please rename to "TurnAngleController.cs" angel->angle

2023-08-17 04:39 UTC, JaXt0r commented on Assets/GothicVR/Scripts/UI/TurnAngelController.cs
> +        Slider turnangelslider = transform.GetComponent<Slider>();
```suggestion
        Slider turnAngleSlider = transform.GetComponent<Slider>();
```

2023-08-18 20:25 UTC, closed without merging