Reactivated running feature, married running feature with settings me…
GothicVRProject/GothicVR pull request #176
Opened 2023-08-03 07:57 UTC by Romeeey

…nu and update walking speeds

# To test
* [ ] Walk in certain speed (slow)
* [ ] Press joystick and check if you are now moving double the speed
* [ ] Press joystick again and check if you are back to normal walking speed
* [ ] Open settings menu, change speed to different value (fast)
* [ ] Press joystick and check if you are now moving double the speed
* [ ] Press joystick again and check if you are back to normal walking speed
* [ ] Try the same with the hands (holding grab and swing arms)

# Checklist
(Please judge for yourself which entry is valuable for your PR)

## Scene
* [ ] FeatureFlags reverted to right value

# Testing
* [ ] Merged _main_ into this branch and tested with the latest features
* [ ] Tested with PCVR
* [ ] Tested with Pico / Quest

## Dependencies
* [ ] If libphoenix-shared.dll is changed, .so is also changed

2023-08-03 11:15 UTC, JucanAndreiDaniel requested changes

2023-08-03 11:15 UTC, JucanAndreiDaniel commented on Assets/GothicVR/Scenes/General.unity
Revert this changes, as it removes the hmd tracking (again)

2023-08-03 11:15 UTC, JucanAndreiDaniel commented on Assets/GothicVR/Scripts/Player/Running/MovementTypeController.cs
> +        public static float running_speed;
Since we need to handle movement stuff also in ClimbProvider, it would be better to have "running speed" set as a constant in ConstantManager

2023-08-03 11:15 UTC, JucanAndreiDaniel commented on Assets/GothicVR/Scripts/Player/Running/MovementTypeController.cs
> +        private const float MIN_VELOCITY_ARM_SWING_ACTIVATE = 0.02f;
maybe increase the value a bit, i just need to rotate my hands and it triggers the arm swinging

2023-08-03 11:15 UTC, JucanAndreiDaniel commented on Assets/GothicVR/Scripts/Player/Running/MovementTypeController.cs
> +            UpdateSpeedVariable(PlayerPrefs.GetFloat(ConstantsManager.I.moveSpeedPlayerPref, 8f));
Please use constants here aswell, maybe even walking speed or running speed

2023-08-03 11:15 UTC, JucanAndreiDaniel commented on Assets/GothicVR/Scripts/Player/Running/MovementTypeController.cs
> +            }
```suggestion
            var speed = _locomotionProvider.moveSpeed == walking_speed ? walking_speed : running_speed;
            SetSpeed(speed);
```

2023-08-03 11:15 UTC, JucanAndreiDaniel commented on Assets/GothicVR/Scripts/Player/Running/MovementTypeController.cs
> +        }
No need to have two functions that do the exact same thing

```suggestion
        private void SetSpeed(float speed)
        {
            _locomotionProvider.moveSpeed = speed;
        }
```

2023-08-03 11:15 UTC, JucanAndreiDaniel commented on Assets/GothicVR/Scripts/UI/MoveSpeedController.cs
> +        MovementTypeController.UpdateSpeedVariable(movespeed);
if we use a constant for speed, then these two are not necessarily needed, at least the second one

2023-11-04 20:21 UTC, JaXt0r commented
@Romeeey is this still valid? As it's stall for three months. Frank mentioned a few changes, but you didn't reply until now.

2023-11-21 05:41 UTC, JaXt0r commented
@JucanAndreiDaniel @Romeeey still a valid branch? If so, please advice. If not, please remove.

2024-01-26 22:15 UTC, Romeeey commented
Is broken due to latest branch. Should be re-implemented from scratch.

2024-01-26 22:15 UTC, closed without merging

2024-05-06 02:06 UTC, JaXt0r commented
@Romeeey  Hygiene: As last commit to this branch is 7 months ago, I will delete it now. But I have a local copy for a couple of days if you want to go on again.