feat: Migrate docs
GothicVRProject/GothicVR pull request #53
Opened 2023-04-24 21:24 UTC by Thogsit

2023-04-24 22:13 UTC, JucanAndreiDaniel requested changes
Looks fine, just a bit more refinement

2023-04-24 22:13 UTC, JucanAndreiDaniel commented on docs/README.md
> +Here you find all the information needed to play or contribute to the game.
```suggestion
Here you will find all the information needed to play or contribute to the game.
```

2023-04-24 22:13 UTC, JucanAndreiDaniel commented on docs/setup/developer.md
> +1. Check the `README.md` file for build instructions
```suggestion
2. Check the `README.md` file for build instructions
```

2023-04-24 22:13 UTC, JucanAndreiDaniel commented on docs/setup/developer.md
> +1. If you built a new version of `libphoenix-shared.dll/.so`, put it into the GothicVR folder at `Assets/GothicVR/Dependencies`
```suggestion
3. If you built a new version of `libphoenix-shared.dll/.so`, put it into the GothicVR folder at `Assets/GothicVR/Dependencies`
```

2023-04-25 04:01 UTC, JaXt0r requested changes

2023-04-27 09:14 UTC, Tyroonis approved these changes

2023-04-27 09:22 UTC, Tyroonis commented
Merged
Adjustments follow in succession issue

2023-04-27 09:22 UTC, merged