Feature/74 additional vob imports for chests ladders etc
GothicVRProject/GothicVR pull request #81
Opened 2023-05-08 06:11 UTC by JaXt0r

More VOBs are now created.

e.g.:
* Benches - rotated right
* fireplace + chickensticks - rotated wrongly
* a lot of furniture in the PSI camp - roated right

I will take care of the rotation stuff later. But you can already use the additional VOBs.

PS: I updated all the shared libraries. Please use them on the main branch.

2023-05-12 10:34 UTC, Tyroonis requested changes
The game crashes at startup.
Is it possible that libraries are missing?

2023-05-12 19:55 UTC, JucanAndreiDaniel commented
> The game crashes at startup. Is it possible that libraries are missing?

Fixed the issue until animations are done properly for Npcs, it was the bones that seem to have caused the crash

2023-05-13 06:28 UTC, Tyroonis approved these changes

2023-05-13 06:28 UTC, merged

2023-05-13 06:29 UTC, Tyroonis commented
Works on Pico4